version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.13.0
  build:
    commands:
       - npm install
       - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: public